myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path("products/", views.product, name='products'),
    path("products/<int:pk>", views.ProductDetailView.as_view(),
         name='product_detail'),
    path("products/add/", views.ProductCreateView.as_view(), name='add_product'),
    path('products/update/<int:pk>',
         views.ProductUpdateView.as_view(), name='update_product'),
    path('products/delete/<int:pk>',
         views.ProductDeteleteView.as_view(), name='delete_product'),
    path('products/mylistings/', views.mylistings, name='mylistings'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('user/', include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = 'user'

urlpatterns = [
    path("register/", views.register, name='register'),
    path("login/", authentication_views.LoginView.as_view(
        template_name='user/login.html'), name='login'),
    path("logout/", authentication_views.LogoutView.as_view(
        template_name='user/logout.html'), name='logout'),
    path("profile/", views.profile, name='profile',),
    path("createprofile/", views.createprofile, name='createprofile'),
    path("sellerprofile/<int:id>", views.sellerprofile, name='sellerprofile'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    seller_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    desc = models.TextField()
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

    # used to redirect the user after using CreateView and UpdateView class base views
    def get_absolute_url(self):
        return reverse('myapp:products')

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profile.jpg",
                              upload_to='profile_pictures')
    phone = models.CharField(max_length=255, default='999 9999 9999')

    def __str__(self) -> str:
        return self.user.username

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'class': 'focus:outline-none', 'placeholder': 'demo@gmail.com'}))
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'focus:outline-none', 'placeholder': 'name'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'focus:outline-none', }))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'focus:outline-none', }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .models import Product

# Create your views here.


def product(request):
    page_obj = products = Product.objects.all()
    product_name = request.GET.get('product_name')
    if product_name != '' and product_name is not None:
        page_obj = products.filter(name__icontains=product_name)

    paginator = Paginator(page_obj, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    # when you decide to use the fn base view rema to use a for loop in html as
    # for product in page_obj ...
    return render(request, 'myapp/index.html', context)
# class based view for the above product view[ListView]


class ProdutListView(ListView):
    model = Product
    template_name = 'myapp/index.html'
    context_object_name = 'products'
    paginate_by = 3


def product_detail(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product': product
    }
    return render(request, 'myapp/details.html', context)
# class based view for the above product detail view[DetailView]


class ProductDetailView(DetailView):
    model = Product
    template_name = 'myapp/details.html'
    context_object_name = 'product'


@login_required
def add_product(request):
    if request.method == "POST":
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        seller_name = request.user
        product = Product(name=name, price=int(price), desc=desc,
                          image=image, seller_name=seller_name)
        product.save()
    return render(request, 'myapp/addProduct.html')
# class based view for creating a user[CreateView]


class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price', 'desc', 'image', 'seller_name']
    # template must be create and named as: product_form.html
    # Also define get_absolute_url in the Product Model for redirecting


def update_product(request, id):
    product = Product.objects.get(id=id)

    if request.method == "POST":
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products/')

    context = {
        'product': product
    }
    return render(request, 'myapp/update.html', context)
# class based view for updating product[UpdateView]


class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price', 'desc', 'image', 'seller_name']
    template_name_suffix = '_update_form'
    # You can give a template sufix as it starts with product_
    # Also define get_absolute_url in the Product Model for redirecting


def delete_product(request, id):
    product = Product.objects.get(id=id)
    context = {
        'product': product
    }

    if request.method == "POST":
        product.delete()
        return redirect('/myapp/products/')

    return render(request, 'myapp/delete.html', context)
# class based for deleting a product [DeleteView]


class ProductDeteleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('myapp:products')
    # Here the success_url deletes the selected product and redirects the user


@login_required
def mylistings(request):
    products = Product.objects.filter(seller_name=request.user)
    context = {
        'products': products,
    }

    return render(request, 'myapp/mylistings.html', context)

user/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Profile

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('myapp:products')

    form = NewUserForm()
    context = {
        'form': form
    }
    return render(request, 'user/register.html', context)


@login_required
def profile(request):
    return render(request, 'user/profile.html')


def createprofile(request):

    if request.method == "POST":
        phone = request.POST.get('contact_number')
        image = request.FILES['upload']
        user = request.user
        profile = Profile(user=user, image=image, phone=phone)
        profile.save()

    return render(request, 'user/createprofile.html')


def sellerprofile(request, id):
    seller = User.objects.get(id=id)
    context = {
        'seller': seller
    }
    return render(request, 'user/sellerprofile.html', context)

myapp/templates/myapp/addProduct.html
{% extends 'myapp/base.html' %} {% block content %}

<h1 class="text-xl font-bold m-10">➕ Add Product</h1>

<form
  method="POST"
  enctype="multipart/form-data"
  class="w-3/5 ml-10 mt-5 shadow-md bg-white px-8 py-10"
>
  {% csrf_token %}
  <div class="mb-7">
    <label for="" class="block text-sm text-gray-500 font-bold mb-2"
      >Product Name</label
    >
    <input
      class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400"
      placeholder="name"
      type="text"
      name="name"
      id="name"
    />
  </div>

  <div class="mb-7">
    <label for="" class="block text-sm text-gray-500 font-bold mb-2"
      >Product Price</label
    >
    <input
      class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400"
      placeholder="price"
      type="text"
      name="price"
      id="price"
    />
  </div>

  <div class="mb-7">
    <label for="" class="block text-sm text-gray-500 font-bold mb-2"
      >Product Desc</label
    >
    <input
      class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400"
      placeholder="desc"
      type="text"
      name="desc"
      id="desc"
    />
  </div>

  <div class="mb-7">
    <label for="" class="block text-sm text-gray-500 font-bold mb-2"
      >Image File</label
    >
    <input
      class="appearance-none py-2 mr-10 text-gray-400"
      type="file"
      accept="image/*"
      name="upload"
      id="upload"
    />
  </div>

  <div class="mb-7">
    <input
      class="bg-green-500 text-white px-5 py-2"
      type="submit"
      name="Add Product"
      value="Add Product"
    />
  </div>
</form>

{% endblock %}

myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet"type="text/css" href="{% static 'myapp/styles.css' %}" />
    <title>Document</title>

    <!-- <meta name="csrf_token" content="{{ csrf_token }}"> -->
  </head>
  <body>
    <nav class="bg-white shadow-lg">
      <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
          <div class="flex space-x-7">
            <div>
              <a href="#" class="flex items-center px-2 py-4">
                <img src="{% static 'myapp/images/shopping.png' %}" alt="" />
                <span class="text-gray-500 font-semibold px-1">Buy&Sell</span>
              </a>
            </div>

            <div class="flex items-center space-x-1">
              <a
                href="{% url 'myapp:products' %}"
                class="px-2 py-4 text-gray-500 font-semibold border-b-4 border-green-500"
                >Home</a
              >
              <a href="{% url 'myapp:add_product' %}" class="px-2 py-4 text-gray-500 font-semibold"
                >Post and Add</a
              >
              <!-- <a href="#" class="px-2 py-4 text-gray-500 font-semibold"
                >Contact</a
              > -->

              <a href="{% url 'myapp:mylistings' %}" class="px-2 py-4 text-gray-500 font-semibold"
                >My Listings</a
              >

              {% if user.is_authenticated %}
              <a href="{% url 'user:profile' %}" class="px-2 py-4 text-gray-500 font-semibold">Profile</a>
                <a href="{% url 'user:logout' %}" class="px-2 py-4 text-gray-500 font-semibold">Logout</a>
              {% else %}
                <a href="{% url 'user:login' %}" class="px-2 py-4 text-gray-500 font-semibold">Login</a>
              {% endif %}


            </div>
          </div>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}
  </body>
</html>

myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-xl font-bold m-10">➕ Delete Product</h1>

<form  method="POST" enctype="multipart/form-data" class="w-3/5 ml-10 mt-5 shadow-md bg-white px-8 py-10">
    {% csrf_token %}
    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="name" value="{{product.name}}" type="text" name="name" id="name">
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="price" value="{{product.price}}" type="text" name="price" id="price">
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Desc</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="desc" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>

    <!-- <div class="mb-7">
        <div class="mb-3">
            <img  class="w-30 h-30" src="{{product.image.url}}" alt="">
        </div>
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Image File</label>
        <input class="appearance-none py-2 mr-10 text-gray-400" type="file" accept="image/*" name="upload" id="upload">
    </div> -->

    <div class="mb-7">
        <input class=" rounded bg-red-500 text-white px-5 py-2" type="submit" name="Edit Product" value="Delete Product">

        <a class="ml-3 text-gray-500 font-bold" href="{% url 'myapp:products' %}">Cancel</a>
    </div>
</form>

{% endblock  %}

myapp/templates/myapp/details.html
{% extends 'myapp/base.html' %} 
{% block content %} 

<div class="flex mt-5 w-3/5">
    <img class="w-1/3" src="{{product.image.url}}" alt="">
    <div class="text-xl ml-5">
        <div>{{product.name}}</div>
        <div class="text-green-500">${{product.price}}</div>
        <div class="text-gray-700">{{product.desc}}</div>
        <div class="text-gray-700"><a href="{% url 'user:sellerprofile' product.seller_name.id %}">Posted by: {{product.seller_name}}</a></div>
        <div class="text-gray-700">Contact: {{product.seller_name.profile.phone}}</div>
    </div>
</div>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %} 

{% load static %}

{% block content %}

<!--Site Hero starts here-->
  <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-12 lg:mt-15 lg:px-8 xl:mt-20">
    <div class="sm:text-center lg:text-left">
      <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
        <span class="block xl:inline">Premium Products</span>
        <span class="block text-green-500 xl:inline">Non-premium Prices</span>
      </h1>
      <p class=" mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg  sm:mx-auto 
      md:mt-5 md:text-2xl flex justify-center">
      Get the best used products across the globe, and enjoy free shipping</p>
    </div>
  </main>
<!--Site Hero ends here-->

<div class="flex mt-5 p-10 justify-center">
  <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
</div>

<div class=" p-10 font-bold" > 
  <h2>Search Products</h2>
  <form method="get">
    <input class=" text-md text-gray-500" type="text" name="product_name" id="product_name" placeholder="type to search">
  </form>
</div>

<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5 ">
  <!--Card-->
  {% for product in page_obj %}
    <a href="{% url 'myapp:product_detail' product.id %}">
      <div class="rounded overflow-hidden shadow-lg">
        <img class="w-full" src="{{product.image.url}}" alt="">
        <div class="px-6 py-4">
          <div class="font-bold text-xl mb-1">{{product.name}}</div>
          <div class="font-bold text-xl mb-1">Posted by:<span class="text-lg text-gray-500"> {{product.seller_name}}</span></div>
          <div class="font-bold text-xl text-green-500 mb-1">${{product.price}}</div>
          <p class="text-gray-700 text-base">{{product.desc}}</p>
        </div>
      </div>
      
    </a>
  {% endfor %} 
  <!--End Card-->
</div>

<!-- pagination code starts here -->
  <div class="pagination flex justify-center items-center mb-20">
    <span>
      {% if page_obj.has_previous %}
      <a class=" m-1 text-sm font-medium flex-inline border px-4 py-2 items-center
      relative text-green-500 border-green-500 z10" href="?page=1">First</a>
      <a class=" m-1 text-sm font-medium flex-inline border px-4 py-2 items-center
      relative text-green-500 border-green-500 z10" href="?page={{page_obj.previous_page_number}}">Previous</a>
      {% endif %}
    </span>

    <span class=" m-1text-sm font-medium flex-inline  px-4 py-2 items-center
    relative text-green-500 z10">
      Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>

    {% if page_obj.has_next %}
      <a class=" m-1 text-sm font-medium flex-inline border px-4 py-2 items-center
      relative text-green-500 border-green-500 z10" href="?page={{page_obj.next_page_number}}">Next</a>
      <a class=" m-1 text-sm font-medium flex-inline border px-4 py-2 items-center
      relative text-green-500 border-green-500 z10" href="?page={{page_obj.paginator.num_pages}}">Last</a>
    {% endif %}
  </div>
<!-- pagination code ends here -->



{% endblock %}

myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="font-bold text-2xl m-10 p-10">🗄️My Listings</div>
    {% for product in products %}
        <div class="itemcontainer flex shadow m-10 p-10">

            <div class="w-1/5">
                <a href="{% url 'myapp:update_product' product.id %}">
                    <img class="w-40 h-40" src="{{product.image.url}}" alt="">
                </a>  
            </div>

            <div class=" w-2/5 font-bold text-gray-700">
                <div>{{product.name}}</div>
                <div class="text-green-500">${{product.price}}</div>
                <div>{{product.desc}}</div>
            </div>

            <div class="w-1/5">
                <a class="rounded bg-green-500 text-white px-5 py-2" href="{% url 'myapp:update_product' product.id %}">
                    Edit Product
                </a>  
            </div>

            <div class="w-1/5">
                <a class=" rounded bg-red-500 text-white px-5 py-2" href="{% url 'myapp:delete_product' product.id %}">
                    Delete Product
                </a>  
            </div>

        </div>
    {% endfor %}
{% endblock  %}

myapp/templates/myapp/product_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-xl font-bold m-10">➕ Delete Product</h1>

<form  method="POST" enctype="multipart/form-data" class="w-3/5 ml-10 mt-5 shadow-md bg-white px-8 py-10">
    {% csrf_token %}
    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="name" value="{{product.name}}" type="text" name="name" id="name">
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="price" value="{{product.price}}" type="text" name="price" id="price">
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Desc</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="desc" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>

    <!-- <div class="mb-7">
        <div class="mb-3">
            <img  class="w-30 h-30" src="{{product.image.url}}" alt="">
        </div>
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Image File</label>
        <input class="appearance-none py-2 mr-10 text-gray-400" type="file" accept="image/*" name="upload" id="upload">
    </div> -->

    <div class="mb-7">
        <input class=" rounded bg-red-500 text-white px-5 py-2" type="submit" name="Edit Product" value="Delete Product">

        <a class="ml-3 text-gray-500 font-bold" href="{% url 'myapp:products' %}">Cancel</a>
    </div>
</form>

{% endblock  %}

myapp/templates/myapp/product_form.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-xl font-bold m-10">➕ Add Product</h1>

<form  method="POST" enctype="multipart/form-data" class="w-3/5 ml-10 mt-5 shadow-md bg-white px-8 py-10">
    {% csrf_token %}
    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Name</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.name}}
        </div>
        <!-- <input  placeholder="name" type="text" name="name" id="name"> -->
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Price</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.price}}
        </div>
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Desc</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.desc}}
        </div>
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Image File</label>      
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.image}} 
        </div>
    </div>

    <div class="hidden shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
        {{form.seller_name}} 
    </div>

    <div class="mb-7">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add Product" value="Add Product">
    </div>
</form>

<!-- {{form.as_p}} -->

{% endblock  %}

myapp/templates/myapp/product_update_form.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-xl font-bold m-10">➕ Update Product</h1>

<form  method="POST" enctype="multipart/form-data" class="w-3/5 ml-10 mt-5 shadow-md bg-white px-8 py-10">
    {% csrf_token %}
    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Name</label>

        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.name}} 
        </div>
        
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Price</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.price}} 
        </div>
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Desc</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.desc}} 
        </div>
    </div>

    <div class="mb-7">
        <div class="mb-3">
            <img  class="w-30 h-30" src="{{product.image.url}}" alt="">
        </div>
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Image File</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
            {{form.image}} 
        </div>
    </div>

    <div class="hidden shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400 w-1/3">
        {{form.seller_name}} 
    </div>

    <div class="mb-7">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Edit Product" value="Edit Product">
    </div>
</form>

{% endblock  %}

myapp/templates/myapp/update.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-xl font-bold m-10">➕ Update Product</h1>

<form  method="POST" enctype="multipart/form-data" class="w-3/5 ml-10 mt-5 shadow-md bg-white px-8 py-10">
    {% csrf_token %}
    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="name" value="{{product.name}}" type="text" name="name" id="name">
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="price" value="{{product.price}}" type="text" name="price" id="price">
    </div>

    <div class="mb-7">
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Product Desc</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-400" placeholder="desc" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>

    <div class="mb-7">
        <div class="mb-3">
            <img  class="w-30 h-30" src="{{product.image.url}}" alt="">
        </div>
        <label for="" class="block text-sm text-gray-500 font-bold mb-2">Image File</label>
        <input class="appearance-none py-2 mr-10 text-gray-400" type="file" accept="image/*" name="upload" id="upload">
    </div>

    <div class="mb-7">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Edit Product" value="Edit Product">
    </div>
</form>

{% endblock  %}

user/templates/user/login.html
{% extends 'myapp/base.html' %}

{% block content %}
    <h1 class="m-5 text-2xl font-bold">👱 Login User</h1>

    <div class="container py-5">
        <form class="w-2/5 bg-white rounded shadow-md px-8 m-5 pb-8 mb-4 pt-6" method="POST">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-500 ">
                    {{form.username}}    
                </div>
            </div>


            <div class="mb-2">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="">Confirm Password</label>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-500 ">
                    {{form.password}}    
                </div>
            </div>

            <button class="bg-green-500 text-white px-5 py-2 rounded" type="submit">Login</button>
        </form>

        <div class="px-5 text-lg text-black-700 mt-3">Do not have an account? <a href="{% url 'user:register' %}" class="text-bold text-green-500">Register</a></div>
    </div>
{% endblock  %}

user/templates/user/logout.html
{% extends 'myapp/base.html' %} 

{% block content %}
<h1>This is the logout page</h1>

{% endblock %}
 

user/templates/user/profile.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="grid p-10 lg:grid-cols-3 sm:grid-cols-1 grid-cols-1">
    <div class="rounded shadow-lg p-5">
        <div>
            <img src="{{ user.profile.image.url}}" alt="" class="w-20 h-20">
        </div>

        <div class="font-bold text-lg px-6 py-2">{{user.username}}</div>
        <div class="font-bold text-lg px-6 py-2">☎️{{user.profile.phone}}</div>
    </div>
</div>
{% endblock  %}